### ISSUE TITLE
HM-MOD-RPI-PCB plötzlich nicht mehr erkannt

### ISSUE THREAD

**Issue by drschnalli** [alexreinert/debmatic#397]
Hey liebe Community... mir ist in den letzten Tagen aufgefallen, dass meine Keymatic FB nicht mehr funktioniert bzw nur noch teilweise... der Präsenzmelder funktionierte seltsamerweise noch... Nun hab ich heute mal reingeschaut in die Console und das HM-MOD-RPI-PCB ist nicht mehr vorhanden bzw. kann der Port nicht geöffnet werden. 

debmatic version: 3.79.6-119
OS:               Armbian 24.11.1 bullseye
Kernel:           6.12.12-current-rockchip64 aarch64
Service Status:   Running
Kernel modules:   Not available
Raw UART dev:     Not available
HMRF Hardware:    unknown
HMIP Hardware:    unknown

Ich vermute dass ich (evtl.... ) mit einem apt-get upgrade was zerschossen hatte.. ich war aber der Meinung dass es schon die ganze Zeit nur noch zur "Hälfte" funktionierte... 

Irgendwas scheint auch mit dem DKMS nicht in Ordnung zu sein.... 

`Disabled DKMS service ... Done
Remove obsolete kernel modules ... Done
Create kernel modules ... FAILED
Check kernel headers ... Done
Prepare kernel headers ... Done
Install DKMS package ... FAILED

Creating symlink /var/lib/dkms/pivccu/1.0.84/source ->
                 /usr/src/pivccu-1.0.84

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j6 KERNELRELEASE=6.12.12-current-rockchip64 ARCH=arm64 all....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.12.12-current-rockchip64 (aarch64)
Consult /var/lib/dkms/pivccu/1.0.84/build/make.log for more information.
Enable DKMS service ... Done`

` detect_radio_module --debug /dev/raw-uart
/dev/raw-uart could not be opened`

`DKMS make.log for pivccu-1.0.84 for kernel 6.12.12-current-rockchip64 (aarch64)
Sat 15 Feb 2025 01:07:59 PM CET
make -C /lib/modules/6.12.12-current-rockchip64/build M=/var/lib/dkms/pivccu/1.0.84/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.12.12-current-rockchip64'
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/dw_apb_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/meson_raw_uart.o
/var/lib/dkms/pivccu/1.0.84/build/eq3_char_loop.c:920:13: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
  920 |  .llseek  = no_llseek,
      |             ^~~~~~~~~
      |             noop_llseek
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/pivccu/1.0.84/build/eq3_char_loop.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.c:150:13: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
  150 |   .llseek = no_llseek,
`
Sorry für den eventuellen Doppelpost... es ist das "bekannte" no_llseek noop_llseek Problem... ich hab mittlerweile versucht all die ganzen Changes manuell in die Dateien einzutragen... auch das mit dem int/void... aber die Kernel Module lassen sich nicht kompilieren... Ich bin mir echt unsicher ob ich nicht einfach zu Bookworm upgrade und den Kernel downgrade... Ich würde hier gerne helfen aber ich bin selbst ein "noop" ... noob :D

**Comment by morlie** [comment]
Die Rasperymatic Module die auch in Debmatic verwendet werden laufen nicht mit dem neuesten Kernel. Nutze  rpi-update um auf einen älteren Kernel zu gehen. Ich habe zurück auf 6.1.21 downgegradet. Damit läuft es wieder. Oder du spielst ein ältere Update zuürck und testest. Vor dem Kernel Spielchen ein Backup machen solltest du dir was zerschießen.

https://github.com/raspberrypi/rpi-update
https://github.com/Hexxeh/rpi-firmware/compare/master...raspberrypi:rpi-firmware:master

Befehl wäre für 6.1.21 z. B.     sudo rpi-update 1440b3e0b52075a9ec244216cddcf56099c28dfa    ... abhängig von deiner Hardware und OS.

**Comment by drschnalli** [comment]
Hey morlie, der Befehl wird aufgrund meines Armbian's nicht funktionieren. Ich nutze einen RockPi 4B mit Armbian.

**Comment by morlie** [comment]
Dann entsprechend des verwendetem OS den Kernel downgraden, alternativ auf die Korrektur warten die am 03.01. zugesichert wurde

**Comment by drschnalli** [comment]
Hab nun alle changes übernommen die module kompilieren auch manuell über den kernel ordner .. jedoch möchte dkms es nicht... 

Error!  Build of dummy_rx8130.ko failed for: 6.12.12-current-rockchip64
